### ISSUE TITLE
Is Docker support imaginary?

### ISSUE THREAD

**Issue by andrew-sol** [raisenational/serverless-dynamodb#15]
It seems like having `docker: true` in the config does not have any impact.
Also, if I run `serverless dynamodb start --docker` it says
```
Error:
Detected unrecognized CLI options: "--docker".
```

The source code does not contain the "docker" word at all.

I've found the following commit: [Add support for running DynamoDB within docker](https://github.com/99x/serverless-dynamodb-local/commit/cc268b928258eb21f9988264d87ed87c0e3d55b1) and the only file changed there is `README.md`. The commit looks like a joke.

So. Has anyone ever tested that Docker support described in `README.md`?

**Comment by domdomegg** [comment]
Re that commit, I think it's because the underlying docker functionality comes from aws-dynamodb-local and the command is supposed to be passed through. However it looks like that pass through is not functioning correctly.
