### ISSUE TITLE
GSI Items Not Created on Seed

### ISSUE THREAD

**Issue by kyusungpark** [raisenational/serverless-dynamodb#27]
Hi, I am tyring to  have GSI items automatically created when dynamodb starts locally. Is this something that is possible? I have noticed that it doesn't populate the items that are in seed for GSI items. 

Love to get some input if possible.
Thank you,

**Comment by domdomegg** [comment]
Hi kyusungpark - I'm not sure I follow what you mean. GSIs replicate data from other tables, so you'd want to seed the items into the original table that the GSI is based off.

If you can provide a code example and more detail about what you're trying to get it to do, I can take another look.

**Comment by kyusungpark** [comment]
Hey, thank you for getting back. I thought GSI items were not being created, but I noticed that I just made a mistake in my query.
