### ISSUE TITLE
UnexpectedParameter errors when using StreamSpecification

### ISSUE THREAD

**Issue by rkaytazov** [raisenational/serverless-dynamodb#29]
An unexpected parameter error is thrown when using StreamSpecification for DynamoDB in an SLS template.
Also FN::IF is unrecognized. 
Deleting the StreamSpecification key-value pair from the object resolves the issue and DDB launches successfully.
<img width="1524" alt="Screenshot 2023-12-08 at 7 34 43" src="https://github.com/raisenational/serverless-dynamodb/assets/75736544/f5cd00c2-67f9-4135-a743-82c359d48021">

This issue is similar to https://github.com/raisenational/serverless-dynamodb/issues/9

The fix here can be applied in the same way for StreamSpecification which worked locally for me
https://github.com/raisenational/serverless-dynamodb/pull/10/files

Would it be possible to have this added as well?
<img width="868" alt="Screenshot 2023-12-08 at 7 43 13" src="https://github.com/raisenational/serverless-dynamodb/assets/75736544/dfcfc962-061b-4c4e-b561-6608f87ba8f3">

Line 341 in index.js

Thank you!

**Comment by domdomegg** [comment]
I've looked into this and I can't reproduce this issue. It looks like DynamoDB's table create command does support `StreamSpecification`:

https://docs.aws.amazon.com/amazondynamodb/latest/APIReference/API_CreateTable.html#DDB-CreateTable-request-StreamSpecification

Are you using other keys within StreamSpecification?

**Comment by domdomegg** [comment]
Closing as stale
