### ISSUE TITLE
This error drive me crazy I just use a uploader as middleware and keep getting this error please help

### ISSUE THREAD

**Issue by queekao** [raisenational/serverless-dynamodb#32]
CLI options definitions were upgraded with "type" property (which could be one of "string", "boolean", "multiple"). Below listed plugins do not predefine type for introduced options:
 - ServerlessDynamodbLocal for "seed"

**Comment by queekao** [comment]
By the way, I don't use any seed option even I set seed to false this error is still showing
serverless-dynamodb:
    port: 8000
    docker: false
    start:
      migrate: true
      seed: false

**Comment by domdomegg** [comment]
Duplicate of #24
