### ISSUE TITLE
Which order is it?

### ISSUE THREAD

**Issue by bitsofinfo** [raisenational/serverless-dynamodb#38]
Per the readme:

This? 

```
plugins:
  - serverless-offline
  - serverless-dynamodb
```

or this

```
plugins:
  - serverless-dynamodb 
  - serverless-offline
```

**Comment by domdomegg** [comment]
For `serverless offline start` to start up dynamodb, I think it needs to be the latter (dynamodb _before_ offline).

Thanks for raising this inconsistency! We should update the docs so it always appears before serverless offline.
